/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button/Button.vue')['default']
    Collapse: typeof import('./src/components/Collapse/Collapse.vue')['default']
    CollapseItem: typeof import('./src/components/Collapse/CollapseItem.vue')['default']
    Dropdown: typeof import('./src/components/Dropdown/Dropdown.vue')['default']
    Form: typeof import('./src/components/Form/Form.vue')['default']
    FormItem: typeof import('./src/components/Form/FormItem.vue')['default']
    Icon: typeof import('./src/components/Icon/Icon.vue')['default']
    Input: typeof import('./src/components/Input/Input.vue')['default']
    Message: typeof import('./src/components/Message/Message.vue')['default']
    Progress: typeof import('./src/components/Progress/Progress.vue')['default']
    Select: typeof import('./src/components/Select/Select.vue')['default']
    Switch: typeof import('./src/components/Switch/Switch.vue')['default']
    Tooltip: typeof import('./src/components/Tooltip/Tooltip.vue')['default']
  }
}

// For TSX support
declare global {
  const Button: (typeof import('./src/components/Button/Button.vue'))['default']
  const Collapse: (typeof import('./src/components/Collapse/Collapse.vue'))['default']
  const CollapseItem: (typeof import('./src/components/Collapse/CollapseItem.vue'))['default']
  const Dropdown: (typeof import('./src/components/Dropdown/Dropdown.vue'))['default']
  const Form: (typeof import('./src/components/Form/Form.vue'))['default']
  const FormItem: (typeof import('./src/components/Form/FormItem.vue'))['default']
  const Icon: (typeof import('./src/components/Icon/Icon.vue'))['default']
  const Input: (typeof import('./src/components/Input/Input.vue'))['default']
  const Message: (typeof import('./src/components/Message/Message.vue'))['default']
  const Progress: (typeof import('./src/components/Progress/Progress.vue'))['default']
  const Select: (typeof import('./src/components/Select/Select.vue'))['default']
  const Switch: (typeof import('./src/components/Switch/Switch.vue'))['default']
  const Tooltip: (typeof import('./src/components/Tooltip/Tooltip.vue'))['default']
}
