allowBuilds:
  '@parcel/watcher': false
  '@sentry/cli': false
  esbuild: false
  puppeteer: false
  sharp: false
  vue-demi: false
onlyBuiltDependencies:
  - sharp
minimumReleaseAgeExclude:
  - xb-element@1.0.6
  - xb-element@1.0.7

minimumReleaseAge: 0

packages:
  - 'packages/*'
  - 'packages/vue/*'
  - 'apps/*'
